<?php
/** @var $block \Mpx\ShipmentInstruction\Block\ShipmentInstruction\Edit */

$shipmentInstructionId=$this->getRequest()->getParam('id');
$shipmentInstruction = $block->getShipmentInstruction($shipmentInstructionId);
$orderQty = $block->getOrderQty($shipmentInstruction->getOrderIncrementId(), $shipmentInstruction->getSku());
$regions = $block->getAllRegions();
$streetData = explode("\n", $shipmentInstruction->getDestinationStreet());
$timeSlots = $block->getTimeSlotConfig($shipmentInstruction['seller_id']);
$csvExportId = $shipmentInstruction->getCsvExportId();
?>
<form action="<?= $block->escapeUrl($block->getUrl('shipmentinstruction/shipmentinstruction/save', ['_secure' => $this->getRequest()->isSecure(), 'form' => 'edit'])) ?>" enctype="multipart/form-data" method="post" id="edit-shipment-instruction" data-form="edit-shipment-instruction" data-mage-init='{"validation":{}}'>
    <div class="wk-mp-design" id="wk-bodymain">
        <fieldset class="fieldset info wk-mp-fieldset">
            <div data-mage-init='{"formButtonAction": {}}' class="wk-mp-page-title legend">
                <span><?= $block->escapeHtml(__('Edit Shipment Instruction')) ?></span>
                <button class="button wk-mp-btn" title="<?= $block->escapeHtml(__('Delete')) ?>" type="submit" id="delete-btn">
                    <span><span><?= $block->escapeHtml(__('Delete')) ?></span></span>
                </button>
                <button class="button wk-mp-btn" title="<?= $block->escapeHtml(__('Save')) ?>" type="submit" id="shipment-instruction-save-btn">
                    <span><span><?= $block->escapeHtml(__('Save')) ?></span></span>
                </button>
                <button class="button wk-mp-btn" title="<?= $block->escapeHtml(__('Duplicate')) ?>" type="submit" formaction="<?= $block->escapeUrl($block->getUrl('shipmentinstruction/shipmentinstruction/duplicate', ['_secure' => $this->getRequest()->isSecure(), 'id' => $this->getRequest()->getParam('id')])) ?>" id="wk-mp-save-duplicate-btn">
                    <span><span><?= $block->escapeHtml(__('Duplicate')) ?></span></span>
                </button>
            </div>
            <?= $block->getBlockHtml('formkey')?>
            <?= $block->getBlockHtml('seller.formkey')?>

            <div class="fieldset wk_mp_fieldset">
                <strong id="order-number"><span><h3><?= /* @noEscape */ __('Order Number') ?></h3></span></strong>
                <?php if ($csvExportId !== null): ?>
                    <div id="invoice-printed-parent">
                        <span id="invoice-printed"><?= /* @noEscape */ __('Invoice printed') ?></span>
                    </div>
                <?php else: ?>
                    <div id="invoice-not-output-parent">
                        <span id="invoice-not-output"><?= /* @noEscape */ __('Invoice not output') ?></span>
                    </div>
                <?php endif; ?>
                <div class="control">
                    <?= $shipmentInstruction->getOrderIncrementId(); ?>
                    <input hidden type="text" class="required-entry input-text" name="entity_id" value="<?= $shipmentInstruction->getEntityId(); ?>"/>
                    <input hidden onchange="checkOrderedQty()" type="text" class="required-entry input-text" name="order_increment_id" id="name" value="<?= $shipmentInstruction->getOrderIncrementId(); ?>"/>
                </div>
            </div>

            <div class="fieldset wk_mp_fieldset">
                <strong><span><h3><?= /* @noEscape */ __('Product Information') ?></h3></span></strong>
                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Product Number')) ?>:</label>
                    <div class="control">
                        <?= $shipmentInstruction->getSku(); ?>
                    </div>
                </div>

                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Product Name')) ?>:</label>
                    <div class="control">
                        <input type="text" class="required-entry input-text ip-change" name="product_name" value="<?= $shipmentInstruction->getProductName(); ?>"/>
                    </div>
                </div>

                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Shipping instruction quantity')) ?>:</label>
                    <div class="control">
                        <input type="text" class="required-entry input-text validate-number ip-change" name="shipping_instruction_qty" id="name" value="<?= $shipmentInstruction->getInstructedQty()?>"/>
                    </div>
                </div>
            </div>

            <div class="fieldset wk_mp_fieldset">
                <strong><span><h3><?= /* @noEscape */ __('Shipping destination info') ?></h3></span></strong>
                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Customer name')) ?>:</label>
                    <div class="control">
                        <input type="text" class="required-entry input-text ip-change" name="customer_name" value="<?= $shipmentInstruction->getDestinationCustomerName();?>"/>
                    </div>
                </div>

                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Zip code')) ?>:</label>
                    <div class="control">
                        <input type="text" class="required-entry input-text validate-postcode ip-change" name="destination_postcode" value="<?= $shipmentInstruction->getDestinationPostcode();?>"/>
                    </div>
                </div>

                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Customer Region')) ?>:</label>
                    <div class="control">
                        <div class="control">
                            <select id="region_id" name="region_id" title="<?= __('State/Province')?>" class="validate-select region_id required-entry ip-change" style="" aria-required="true" defaultvalue="0">
                                <option value=""><?= /* @noEscape */ __('Please select a region, state or province.') ?></option>
                                    <?php foreach ($regions as $region):?>
                                        <option <?=($region['name'] == $shipmentInstruction->getDestinationRegion()) ? "selected" : ''?> value="<?=$region['name'];?>"><?=$region['name'];?></option>
                                    <?php endforeach;?>
                            </select>
                            <input type="text" id="region" name="region" value="" title="<?= __('State/Province')?>" class="input-text" style="display:none;" autocomplete="off" aria-required="true">
                        </div>
                    </div>
                </div>

                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Customer City')) ?>:</label>
                    <div class="control">
                        <input type="text" class="required-entry input-text ip-change" name="customer_city" value="<?= $shipmentInstruction->getDestinationCity();?>"/>
                    </div>
                </div>

                <div class="field required">
                    <label class="label"><?= $block->escapeHtml(__('Customer Street')) ?>:</label>
                    <div class="control">
                        <input type="text" class="required-entry input-text ip-change" name="customer_street[]" value="<?= !empty($streetData[0]) ? $streetData[0] : " ";?>"/>
                    </div>
                </div>

                <div class="field">
                    <label class="label"><?= $block->escapeHtml(__('Customer Room Number')) ?>:</label>
                    <div class="control">
                        <input type="text" class="required-entry input-text ip-change" name="customer_street[]" value="<?= !empty($streetData[1]) ? $streetData[1] : "" ;?>"/>
                    </div>
                </div>

                <div class="field">
                    <label class="label"><?= $block->escapeHtml(__('Delivery Company')) ?>:</label>
                    <div class="control">
                        <?= $block->getDeliveryCompanyName($block->getRequest()->getParam('id')); ?>
                    </div>
                </div>

                <div class="field">
                    <label class="label"><?= $block->escapeHtml(__('Invoice Type')) ?>:</label>
                    <div class="control">
                        <?= $block->getInvoiceType($block->getRequest()->getParam('id')); ?>
                    </div>
                </div>

                <div class="field">
                    <label class="label"><?= $block->escapeHtml(__('Estimated ship date')) ?>:</label>
                    <div class="control">
                        <input type="date" class="input-text ip-change" name="scheduled_shipping_date" value="<?= $shipmentInstruction->getScheduledShippingDate() == null ? "" : date('Y-m-d', strtotime($shipmentInstruction->getScheduledShippingDate())); ?>" />
                    </div>
                </div>

                    <table class="table time-slot">
                        <thead>
                        <tr>
                            <th class="desired_shipping_date_time" data-bind="i18n: 'Date/Day'" style="text-align:center"><?= $block->escapeHtml(__('Desired shipping date time')) ?></th>
                            <th class="desired_shipping_date_time" data-bind="i18n: 'Delivery Time Slots'"><?= $block->escapeHtml(__('Desired shipping date time')) ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="slot-row">
                            <td>
                                <select name="desired_delivery_date" class="ip-change">
                                    <option value=""><?=$block->escapeHtml(__('None')) ?></option>
                                    <?php for ($count = 0; $count < $block->getMaxDaysTimeSlotConfig(); $count++) { $dataDate = date('Y-m-d', strtotime($block->getStartDayShip(). ' + '.$count.' days')); ?>
                                        <option <?= ($dataDate == $shipmentInstruction->getDesiredDeliveryDate()) ? "selected" : "";?> value="<?=$dataDate?>"><?= date('Y年m月d日', strtotime($block->getStartDayShip(). ' + '.$count.' days')); ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>
                                <select name="desired_delivery_time" class="ip-change">
                                    <option value=""><?=$block->escapeHtml(__('None')) ?></option>
                                    <?php foreach ($timeSlots as $slot) : $dataTime = $block->getFormatTime($slot->getStartTime()) . " - " . $block->getFormatTime($slot->getEndTime());?>
                                        <option <?=($dataTime == $shipmentInstruction->getDesiredDeliveryTime()) ? "selected" : "";?> value="<?=$dataTime?>"><?=$dataTime;?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
                        </tr>
                        </tbody>
                    </table>

            </div>

            <div class="fieldset wk_mp_fieldset">
                <strong><span><h3><?= /* @noEscape */ __('Last update datetime') ?></h3></span></strong>
                <div class="control">
                    <?= $block->formatDate($shipmentInstruction->getUpdatedAt(), \IntlDateFormatter::MEDIUM, true, $block->getTimezoneForStore($shipmentInstruction->getUpdatedAt()));?>
                </div>
            </div>

            <div class="fieldset wk_mp_fieldset">
                <strong><span><h3><?= /* @noEscape */ __('Created datetime') ?></h3></span></strong>
                <div class="control">
                    <?= $block->formatDate($shipmentInstruction->getCreatedAt(), \IntlDateFormatter::MEDIUM, true, $block->getTimezoneForStore($shipmentInstruction->getCreatedAt()));?>
                </div>
            </div>

        </fieldset>
    </div>
</form>
<div class="buttons-set">
    <p class="back-link">
        <a href="<?= $block->getUrl('shipmentinstruction/shipmentinstruction/index') ?>" class="left">&laquo; <?= /* @noEscape */ __('Back to Shipping Instruction List') ?></a>
    </p>
</div>
<div id="modal-content">
    <div class="modal-inner-content">
        <p><?=  /* @noEscape */ __("The total number of shipping orders exceeds the number of orders.")?></p>
    </div>
</div>
<div id="modal-csv-export-id-warning">
    <div class="modal-inner-content">
        <p><?=  /* @noEscape */ __("This shipping data has already been output as an invoice CSV. If you want to change it, please output it from the new creation menu of the invoice label CSV output menu.")?></p>
    </div>
</div>
<div id="modal-scheduled-shipping-date-warning">
    <div class="modal-inner-content">
        <p><?=  /* @noEscape */ __("You have entered a shipping date that is in the past.")?></p>
    </div>
</div>
<div id="modal-delete-warning">
    <div class="modal-inner-content">
        <p><?=  /* @noEscape */ __("Delete shipping instruction data.")?></p>
    </div>
</div>

<script>
    require([
        "jquery",
        "XShoppingSt_Marketplace/catalog/type-events"
    ], function($, TypeSwitcher){
        var $form = $('[data-form=edit-product]');
        $form.data('typeSwitcher', TypeSwitcher.init());
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "XShoppingSt_Marketplace/js/product/weight-handler": {},
            "XShoppingSt_Marketplace/catalog/apply-to-type-switcher": {}
        }
    }
</script>
<script type="text/x-magento-init">
        {
            "*": {
                "editShipmentWarning": {
                    "shipmentTitle" : "<?= __('Shipping Instruction Warning')?>",
                    "buttonContinue" : "<?= __('Continue')?>",
                    "buttonCancel" : "<?= __('Cancel')?>",
                    "buttonClose" : "<?= __('Close')?>",
                    "buttonConfirm" : "<?= __('OK')?>",
                    "orderQty" : "<?= (int)$orderQty;?>",
                    "csvExportId" : "<?= $csvExportId; ?>",
                    "recordId" : "<?= $block->getRequest()->getParam('id') ; ?>"
                }
            }
        }
</script>

