<?php
if ($block->isShippineAvlForSeller()) { ?>
    <li data-ui-id="menu-x-shopping-st-marketplace-shipsetting-menu" class="item-menu parent level-1">
        <strong class="wk-mp-submenu-group-title">
            <span><?= /* @noEscape */ __('Shipping Settings')?></span>
        </strong>
        <div class="wk-mp-submenu">
            <ul>
                <?= $block->getChildHtml();?>
            </ul>
        </div>
    </li>
<?php } ?>
