volumes:
  mysql_data:

networks:
  x_shopping_st:
    external: true

services:

  app:
    build:
      context: ../../
      dockerfile: dev/docker/app/Dockerfile
      args:
        - HOST_NAME=${HOST_NAME}
        - UID=${UID}
        - GID=${GID}
    hostname: ${HOST_NAME}
    working_dir: /var/www/html
    tmpfs: /var/lib/varnish/varnishd:exec
    volumes:
      - ./../../:/var/www/html
    env_file:
      - .env
    expose:
      - 80
    networks:
      - x_shopping_st
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
