networks:
  x_shopping_st:
    external: true

services:
  nginx:
    build:
      context: proxy
      dockerfile: ./Dockerfile
    restart: always
    hostname: dev-reverse-proxy.x-shopping-st.com
    working_dir: /etc/nginx/
    volumes:
      - ./proxy/conf.d/reverse-ptoxy.conf:/etc/nginx/conf.d/reverse-ptoxy.conf
      - ./proxy/html:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - x_shopping_st
