volumes:
  mysql_data:

networks:
  x_shopping_st:
    external: true

services:

  varnish:
    build:
      context: ../../
      dockerfile: ./dev/docker/varnish/Dockerfile
      args:
        - HOST_NAME=${HOST_NAME}
    hostname: ${VARNISH_HOST_NAME}
    tmpfs: /var/lib/varnish/varnishd:exec
    expose:
      - 80
    networks:
      - x_shopping_st
    depends_on:
      - apache_php
      - mysql

  apache_php:
    build:
      context: ../../
      dockerfile: ./dev/docker/apache-php/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    hostname: ${HOST_NAME}
    working_dir: /var/www/html
    volumes:
      - ./../../:/var/www/html
    env_file:
      - .env
    expose:
      - 80
    networks:
      - x_shopping_st
    depends_on:
      - mysql

  mysql:
    build:
      context: ./
      dockerfile: ./mysql/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    hostname: ${MYSQL_HOST}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306
    networks:
      - x_shopping_st
